### ISSUE TITLE
Not able to view shortcuts

### ISSUE THREAD

**Issue by chrisberthe** [killalau/vscode-liquid-snippets#1]
I have VS Code Version `1.8.1`. I downloaded the extension directly from the editor, created an `index.liquid` and tried some shortcuts - can't get it to work 😢.

I've also tried removing all my plugins, resetting my settings (not that I think those would have an effect on the extension, but I tried nonetheless).

![image](http://g.recordit.co/WKcbs1LHEq.gif)

**Comment by killalau** [comment]
I forget to add the prerequisite, please also install the extension:
https://marketplace.visualstudio.com/items?itemName=neilding.language-liquid

Hope this help

**Comment by chrisberthe** [comment]
Unfortunately it leads to the same thing.

**Comment by killalau** [comment]
In the `Language Mode` can you found `HTML Liquid`?
(Win) Ctrl + Shift + P -> Change Language Mode -> HTML Liquid
(Mac) Command + Shift + P -> Change Language Mode -> HTML Liquid

I've VS Code `1.8.1` on Mac, not sure if it is setting issue, or specific environment, or something I missed.

**Comment by chrisberthe** [comment]
That did the trick. The two main culprits I had were:

1. I hadn't installed _Liquid Languages Support_.
2. In my `settings.json` I had a left over property from the old days when Liquid wasn't really supported in VS Code yet and was using Twig as the highlighter for Liquid files:

```json
"files.associations": {
    "*.liquid": "twig"
}
```

Thanks @killalau!
