### ISSUE TITLE
Can we get the new section schema tags please

### ISSUE THREAD

**Issue by ConduciveMammal** [killalau/vscode-liquid-snippets#10]
I'm wondering if the new section schema tags can be added?

-  `{% schema %}{% endschema %}`
- `{% stylesheet %}{% endstylesheet %}`
- `{% javascript %}{% endjavascript %}`

Maybe also some larger code expansion on the `{% schema %}` tag where it expands with some default schema?
```
{% schema %}
{
   "name": "section",
   "settings": [],
   "blocks": [],
   "presets": [],
}
{% endschema %{
````

**Comment by killalau** [comment]
What if we have 3 sets of schema tag, `schema`, `schema-empty` and `schema-locales`. And also we have `stylesheet` and `stylesheet-scss`. I've a long time didn't code with liquid, not sure if this help.
```
// schema
{% schema %}
{
   "name": "section",
   "settings": [],
   "blocks": [],
   "presets": [],
   "default": {}
}
{% endschema %}

// schema-empty
{% schema %}
{}
{% endschema %}

// schema-locales
{
   "locales": {
      "en": {
        "title": "Welcome"
      }
   }
}

// stylesheet
{% stylesheet %}
{% endstylesheet %}

// stylesheet-scss
{% stylesheet 'scss' %}
{% endstylesheet %}
```

**Comment by panoply** [comment]
I’ve got a PR that provides simple snippets for this if anyone can merge, that would be great. Thanks.

**Comment by killalau** [comment]
merged with little modification.

**Comment by panoply** [comment]
Thanks @killalau! You're a legend.
