### ISSUE TITLE
Basic emmet html autocomplete does not work with this

### ISSUE THREAD

**Issue by ghost** [killalau/vscode-liquid-snippets#11]
How can I get the basic emmet autocomplete snippets to work with this, that are built into vs code? When I'm on an HTML Liquid template, I can no longer type "div.class-name + tab" for example. Liquid autocompletes are convenient but not at the cost of losing all html autocompletes.

**Comment by MPMachado** [comment]
Found a solution. 

User Settings
`"emmet.includeLanguages": {
        "liquid": "html"
    },`

**Comment by killalau** [comment]
Thanks a lot, I'll add this to readme, and let more people to know.
