### ISSUE TITLE
Drop external dependency of vscode-liquid

### ISSUE THREAD

**Issue by panoply** [killalau/vscode-liquid-snippets#13]
Liquid snippets has an external dependency on [vscode-liquid](https://marketplace.visualstudio.com/items?itemName=neilding.language-liquid). Is this really necessary? Do snippet extensions require external dependencies?

I have an [extension](https://github.com/panoply/vscode-shopify-liquid) which provides liquid syntax support but due to the external dependency this extension has on  [vscode-liquid](https://marketplace.visualstudio.com/items?itemName=neilding.language-liquid)  users are unable to uninstall vscode-liquid when using vscode-liquid-snippets. This leads to duplicate support of liquid syntax with potential to create conflicting issues when users have both syntax extensions installed. 

To combat this issue my extension for the time being uses a forked version of this project but this will lead to uninstalls of vscode-liquid-snippets which I would like to avoid because this project is great and my extension should not have to use a forked version just because of an external dependency.

Dropping vscode-liquid as an external dependency means other extensions that support liquid syntax variations won't run into issues or in my case not require forking.

**Comment by killalau** [comment]
Updated in 2.0.0
