### ISSUE TITLE
Cannot use liquid snippets

### ISSUE THREAD

**Issue by BillRaymond** [killalau/vscode-liquid-snippets#17]
As per the instructions, I installed the Liquid Languages Support (Neil Ding). Then I installed Shopify Liquid Template Snippets. I also *think* I properly configured the user settings, searching for *emmet* and then selecting *include languages*.

I quit VSC and re-opened (also just tried a reload). I go into a previously saved or new and saved HTML file or Markdown file (not sure if Markdown is supported), and then typed "assign". I pressed enter and tab, but nothing occurs. According to the readme, I can also enable with *command+space* on the Mac, but that opens up Spotlight Search. I tried *control+space*, which is what I think the documentation means to require, but that does not result in showing liquid support.

I cannot seem to get up and running. Any help you can provide would be useful.

Thanks.

**Comment by killalau** [comment]
Can you see the `HTML Liquid` file type in the status bar? or when you click on it, can you find this option?

<img width="462" alt="Screenshot 2020-06-18 at 11 01 12 AM" src="https://user-images.githubusercontent.com/3831789/84973222-2d61af80-b153-11ea-9a15-970acea9f785.png">

If there is such option, which means `Liquid Languages Support` is install successfully, and vise versa. If your files are not automatically map to `liquid` programming language, you may need to check the `files.associations` settings, whether you map you files to `liquid`. The code snippet is only work on `liquid` files.

**Comment by BillRaymond** [comment]
Okay, that did the trick. Thank you!
