### ISSUE TITLE
Old Style Tag?

### ISSUE THREAD

**Issue by bullshit-media** [killalau/vscode-liquid-snippets#18]
Shouldn't it be `{% style %}` instead of `{% stylesheet %}` 

Source: https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags#style

P.S. I'm new to Shopify, so I can be wrong.

**Comment by killalau** [comment]
It is a different tag.
https://shopify.dev/tutorials/develop-theme-use-sections#javascript-and-stylesheet-tags

P.S. I didn't code Shopify theme for some years, please make pull request if you have any suggestion.
