### ISSUE TITLE
When I use this extension, I cannot use HTML/Javascript autocompletion

### ISSUE THREAD

**Issue by snowsky** [killalau/vscode-liquid-snippets#7]
I can't get a .liquid page to recognize the liquid syntax as well as html and javascript. Is there any conflict between extensions or it is by design? Thanks.

**Comment by killalau** [comment]
sorry @snowsky, it is the limitation of this extension. If you have any idea how to improve it, please tell me, thanks.

**Comment by killalau** [comment]
let's close this issue first, seems we don't have an idea right at a short moment.

**Comment by Webb-developer** [comment]
Any update on this? Is it the extension or VS code itself? Atom seems to handle this situation perfectly and the liquid syntax package is also based on Siteleaf.
